### PR TITLE
fix broken retry (RT#122131)

### PR DESCRIPTION
**Pull request by abraxxa**
I've done the fix in two commits, one adding a test for the bug and the direct fix and a second that fixes the aftermath of that first fix.
Feel free to contact me if I should merge the two commits before applying the pull request.

### CODE REVIEW

**Comment by abraxxa** [comment]
Guys I need a fixed version released and would take over co-maint if required. Thanks!

**Comment by rcaputo** [comment]
Thanks. Merged and released version 1.175 to PAUSE.

**Comment by abraxxa** [comment]
Thank you VERY MUCH Rocco!

**Comment by abraxxa** [comment]
You can also close RT#122131.

**Pull request merged**
